### ISSUE TITLE
ppx_jane doesn't appear to work

### ISSUE THREAD

**Issue by yminsky** [janestreet/toplevel_expect_test#2]
It looks like toplevel_expect_test doesn't work with syntax extensions.  In particular, this:

```
#verbose true
#require "core"
#require "ppx_jane"
open Core.Std;;
let x = [%sexp_of: int]
```

Fails with this:

```
No newline at the end of z.ml.corrected
------ z.ml
++++++ z.ml.corrected
File "z.ml", line 7, characters 0-1:
 |#verbose true
 |#require "core"
 |#require "ppx_jane"
 |open Core.Std;;
 |let x = [%sexp_of: int]
 |       
+|[%%expect{|
+|Line _, characters 10-17:
+|Extension `sexp_of' was not translated
+||}]
```

**Comment by ghost** [comment]
Indeed, I set up things so that rewriters are executed in-process. This is nice to test rewriters themselves: you can register a rewriter and test it immediately. I'll look into making both internal and external rewriters work nicely. In the meantime you can do this before loading ppx_jane:

``` ocaml
#predicates "ppx_driver"
```

this will force ocamlfind to consider the various ppx_\* packages as libraries rather than just -ppx options.

Note that this last method is faster anyway as you don't spawn 10 processes per line.

**Comment by yminsky** [comment]
Ah, fantastic.  Maybe we can just document the fact that the #predicates call is required.  But with that, it works like a charm.

**Comment by ghost** [comment]
I added `#predicates` by default in the latest minor release
